// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: watchers.sql

package db

import (
	"context"
)

const createWatcher = `-- name: CreateWatcher :one
INSERT INTO watchers (hash_uri)
VALUES ($1)
RETURNING watcher_id
`

func (q *Queries) CreateWatcher(ctx context.Context, hashUri string) (int64, error) {
	row := q.db.QueryRow(ctx, createWatcher, hashUri)
	var watcher_id int64
	err := row.Scan(&watcher_id)
	return watcher_id, err
}

const getWatcher = `-- name: GetWatcher :one
SELECT watcher_id
FROM watchers w
WHERE w.hash_uri = $1
`

func (q *Queries) GetWatcher(ctx context.Context, hashUri string) (int64, error) {
	row := q.db.QueryRow(ctx, getWatcher, hashUri)
	var watcher_id int64
	err := row.Scan(&watcher_id)
	return watcher_id, err
}
